server:
  port: 8080

  
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  autoconfigure:
      exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      
rabbit:
  username: admin
  password: admin
  host: localhost
  queueManagnent: microservice-management
  queueMicroservice: management-microservice
  rpcQueue: rpc_queue

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  file: management-app/logs/management.log