server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
rabbit:
  username: admin
  password: admin
  host: localhost
  queueManagnent: microservice-management
  queueMicroservice: management-microservice

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  file: management-app/logs/management.log