server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: WEB-INF/
      suffix: .jsp
      
rabbit:
  username: admin
  password: admin
  host: localhost
  queueManagnent: microservice-management
  queueMicroservice: management-microservice