spring:
  profiles:
    active: hello-world,sender
  mvc:
    view:
      prefix: WEB-INF/
      suffix: .jsp

ogging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
    
server:
  port: 8090


# spring.mvc.view.prefix: WEB-INF/
# spring.mvc.view.suffix: .jsp