server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    dialect: org.hibernate.dialect.MySQL5Dialect
    
rabbit:
  username: admin
  password: admin
  host: localhost
  queueManagnent: microservice-management
  queueMicroservice: management-microservice
  rpcQueue: rpc_queue

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG

  file: microservice/logs/microservice.log

